apiVersion: v1
kind: Service
metadata:
  name: cdc-docker-consumer
  labels:
    app: cdc-docker-consumer
spec:
  selector:
    app: cdc-docker-consumer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
